Repository Conscious-Coders/Alt-Lane, pull requests merged in 2021-04, with the labels that each got.

#51 registration page-advanced
  client/src/Pages/Register.js
Labels: frontend

#56 add links to navigate through pages
  client/public/alt-lanewhite.png
  client/public/index.html
  client/public/logo.png
  client/src/App.js
  client/src/Components/LandingNavBar.js
  client/src/Components/MenteeNavBar.js
  client/src/Components/MentorNavBar.js
  client/src/Pages/Login.js
  client/src/Pages/Register.js
Labels: frontend

#76 (fix) fixed redirect to login
  client/package.json
  client/src/Pages/Register.js
Labels: bug, frontend

#79 (refactor) created auth context to pass down authentication
  client/src/App.js
  client/src/Pages/FindMentor.js
  client/src/Pages/Homepage.js
  client/src/Pages/Login.js
Labels: enhancement, frontend

#84 (fix) backend routes bug, implemented mentee register
  api/routes/mentee_interests.js
  api/routes/mentees.js
  api/routes/mentors.js
  api/routes/users.js
  client/src/App.js
  client/src/Pages/Register.js
Labels: backend, bug, enhancement, frontend

#87 (fix) mentor profile data not being displayed
  client/src/Pages/Profile.js
Labels: bug

#88 Feat tracey authorization fix
  api/app.js
  api/middleware/verifytoken.js
  api/package.json
  api/routes/mentorship.js
  api/routes/users.js
  client/package.json
  client/src/Components/MentorCard.js
  client/src/Pages/FindMentor.js
  client/src/Pages/Login.js
  client/src/Pages/Profile.js
Labels: bug

#89 Feat/home fetch
  client/src/App.js
  client/src/Components/HomeCard.js
  client/src/Components/MenteeNavBar.js
  client/src/Components/MentorNavBar.js
  client/src/Pages/FindMentor.js
  client/src/Pages/Homepage.js
  client/src/Pages/Login.js
  client/src/Pages/Profile.js
Labels: bug

#93 Update Profile.js
  client/src/Pages/Profile.js
Labels: enhancement, frontend

#99 (bug) fix bug that caused too many rerenders & not displaying all data
  client/src/Pages/Homepage.js
  client/src/Pages/scratch.js
Labels: bug, frontend

#102 Feat tracey parent confirmation nodemailer
  api/app.js
  api/bin/www
  api/mailer.js
  api/middleware/verifytoken.js
  api/package-lock.json
  api/package.json
  api/routes/mentorship.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Chat.js
  client/src/Pages/Homepage.js
  client/src/Pages/Landing.js
  client/src/Pages/Register.js
  client/src/Pages/Settings.js
  client/src/Pages/VerifyEmail.js
Labels: backend, enhancement, frontend

#104 Feat tracey parent mentor mentee connection nodemailer
  api/app.js
  api/bin/www
  api/mailer.js
  api/middleware/verifytoken.js
  api/package-lock.json
  api/package.json
  api/routes/mentorship.js
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/Chat.js
  client/src/Pages/Homepage.js
  client/src/Pages/Landing.js
  client/src/Pages/Register.js
  client/src/Pages/Settings.js
  client/src/Pages/VerifyEmail.js
Labels: backend, enhancement, frontend

#105 Refactor/get mentee interests
  client/src/Components/HomeCard.js
  client/src/Pages/Homepage.js
Labels: enhancement, frontend

#113 add styling for register
  api/package-lock.json
  client/package-lock.json
  client/package.json
  client/src/Components/Button.js
  client/src/Components/MentorCard.js
  client/src/Pages/Register.js
  client/src/Pages/Register.scss
Labels: enhancement, frontend

#116 remove unused functions
  client/src/Pages/Register.js
  client/src/Pages/Register.scss
Labels: documentation, frontend

#124 implement chat functionality
  api/socket.js
  client/src/App.js
  client/src/Components/Chat/Chat.js
  client/src/Components/HomeCard.js
  client/src/Components/useChat.js
  client/src/Pages/Homepage.js
Labels: backend, enhancement, frontend

#125 Fix/styling chat
  api/socket.js
  api/utils/chatUsers.js
  client/src/App.js
  client/src/Components/Chat/Chat.css
  client/src/Components/Chat/Chat.js
  client/src/Components/HomeCard.js
  client/src/Components/InfoBar/InfoBar.css
  client/src/Components/InfoBar/InfoBar.js
  client/src/Components/Input/Input.css
  client/src/Components/Input/Input.js
  client/src/Components/Message/Message.css
  client/src/Components/Message/Message.js
  client/src/Components/Messages/Messages.css
  client/src/Components/Messages/Messages.js
  client/src/Components/TextContainer/TextContainer.css
  client/src/Components/TextContainer/TextContainter.js
Labels: frontend

#131 add user's name to chat messages
  api/routes/users.js
  client/src/App.js
  client/src/Components/Chat/Chat.js
  client/src/Components/HomeCard.js
  client/src/Components/Messages/Messages.css
  client/src/Components/Messages/Messages.js
  client/src/Pages/Homepage.js
  client/src/Pages/Register.js
  client/src/Pages/Register.scss
  client/src/Pages/Settings.js
Labels: frontend

#157 (fix) landing styling
  client/public/Images/TraceySlides.png
  client/public/Images/dillenSlides.png
  client/public/Images/flyArrows.jpeg
  client/public/Images/joliSlides.png
  client/public/Images/ladyArrows.jpeg
  client/public/Images/lightPath.png
  client/public/Images/mentorship.png
  client/public/Images/shrutiSlides.png
  client/public/Images/student_debt.jpeg
  client/public/Images/student_debt.png
  client/public/index.html
  client/src/App.css
  client/src/Components/Footer.js
  client/src/Components/InfoCard.js
  client/src/Components/LandingSlide.js
  client/src/Pages/Landing.js
  client/src/Pages/Register.js
Labels: frontend

#162 Feat/dillen add register route
  api/routes/career_fields.js
  api/routes/mentees.js
  api/routes/mentors.js
  api/routes/mentorship.js
  api/routes/users.js
Labels: backend, enhancement

#167 Feat/dillen/refactor register route on register page
  api/routes/users.js
  client/src/Pages/Register.js
Labels: backend
